* How this is all getting organized
** CRN Model
*** Classes:
    Overall we need to keep track of:
     - Window size
     - Starting positions
     - Starting velocities
     - Bounce angles
     - Species
     - Reactions
     - Rate constants
    to create reproducable reactions, and as such our model should account for these.

**** Molecule:
     - Not imported from .cps model
     - Tied to/inheits some gosu object
     - _list[list[int]]_ bounce offsets in form (x,y)
     - _point_ start_pos -- starting position -- immutable
     - _point_ start_velocity -- starting velocity -- immutable
     - _point_ cur_pos -- current position -- mutable
     - _point_ cur_velocity -- current velocity -- mutable
         
**** Species:
     - Seperatly keep track of a list of all frames at which changes occur
     - _Gosu::Color_ color -- color of the Molecule
     - _str_ label -- displayed string on top of all molecules of this type
     - _str_ name -- Species name - must be unique
     - _dict_ counts -- Dict with a new _int_ at every frame where the count of this species changes for graphing purposes
     - _list[molecule]_ molecules -- a list of all molecules that are a part of this species at any point in time
     - Null is not needed - just say things go to nothing
**** CRN:
     - Keep track of the reaction network
     - _list[molecule] -- current molecules we have -- mutable
     - _list[species] -- current species we have -- mutable
     - _dict_ reactions --dictionary of reactions -- mutable
     
     **** Reaction dictionary:
          - _list[str_name]_ --list of names for reactants
          - _list[_point_ rateConstant, list[str_name]] --rate constant and list of names of products
   

**** TODO: Graphics class nonsense

*** Problems to solve:
**** Graphics
     - How do we keep track of how the molecules split?
       - Maybe they always go out the same way (i.e. same angle between all) 
            Sounds good
     - How do we make sure that they don't immediately collide upon splitting?
     
     - How do we handle the speed of a reaction? Do molecules sometimes not react when the collide?
        Yes, based on discussion with Prof. Klinge we can treat rate constant as
            - bimolecular reaction: the probability that when the two molucules collide that the reaction will occur
            - single molucule reaction: treat the rate constant as minimal time to elapse before a reaction can occur
              to simplify: the reaction always takes place at the end of the time interval
              future plans: before time elapse probability of reaction is zero, after minimal time elapse probability is greater than zero and keeps increasing utill probability is 1 or the reaction occurs
     - What, if anything, gets shown alongside the reaction as it executes?
        nothing, we can make the reactions instantaneous
